# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Positly blog
email: skorulis@gmail.com
description: > # this means to ignore newlines until "baseurl:"

timezone: Australia/Sydney
url: "https://positly.com" # the base hostname & protocol for your site
twitter_username: skorulis
github_username:  skorulis

# Build settings
markdown: kramdown
